import {extract,validate,render,emphasisFor} from './engine.js';
const $=id=>document.getElementById(id);
const sample=`ただいま。\nおかえり。\nここにいる。\nお前の声を、聞かせて。\n今夜は、もう少しだけ。\n一緒に帰ろう。\nこの続きを、何度でも。\n忘れたくない言葉がある。\n名前を呼んで。\n好きだよ。\n隣を歩く。\n今日は、どんな一日だった？\n大丈夫、ちゃんと聞いている。\nゆっくりでいい。\n言葉にしてくれて、ありがとう。\nその話、もっと聞きたい。\n僕は強い。\nまた明日も、ここで。\n星が見える。\n手を繋ごう。\n一緒に笑っていたい。\nお前が選んだ、その先へ。\nお茶にしよう。\nあの日のことを覚えている。\nまだ、話していたい。\n大切な言葉を、この一枚に。`;
let seed=crypto.getRandomValues(new Uint32Array(1))[0],mono=false,busy=false,pending=false,lastResult=null,timer,toastTimer,fontNumber=0,revision=0;
const families={serif:'"Yu Mincho", "Hiragino Mincho ProN", "Noto Serif CJK JP", serif',sans:'"Yu Gothic", "Hiragino Kaku Gothic ProN", "Noto Sans CJK JP", sans-serif'};
let phraseList=[],emphasisModes=[];
const phrases=()=>phraseList.map(t=>t.trim()).filter(Boolean);
function editPhrases(){const holder=$('phrases');holder.replaceChildren();phraseList.forEach((text,i)=>{const row=document.createElement('div');row.className='phrase-row';const input=document.createElement('textarea');input.value=text;input.rows=Math.min(6,Math.max(2,text.split('\n').length));input.setAttribute('aria-label','ことば '+(i+1));input.addEventListener('input',()=>{phraseList[i]=input.value;status();schedule();});const remove=document.createElement('button');remove.className='text-button';remove.textContent='削除';remove.setAttribute('aria-label','ことば '+(i+1)+' を削除');remove.onclick=()=>{phraseList.splice(i,1);emphasisModes.splice(i,1);editPhrases();status();schedule();};const controls=document.createElement('div');controls.className='phrase-controls';const emphasis=document.createElement('select');emphasis.setAttribute('aria-label','ことば '+(i+1)+' の強調');[['auto','自動'],['strong','強調'],['normal','通常']].forEach(([value,label])=>emphasis.add(new Option(label,value)));emphasis.value=emphasisModes[i]||'auto';emphasis.onchange=()=>{emphasisModes[i]=emphasis.value;status();schedule();};const badge=document.createElement('small');badge.className='emphasis-badge';badge.dataset.index=String(i);controls.append(emphasis,badge,remove);row.append(input,controls);holder.append(row);});}
$('phrase-add').onclick=()=>{phraseList.push('');emphasisModes.push('auto');editPhrases();$('phrases').lastElementChild.querySelector('textarea').focus();status();};
function status(){const list=phrases();document.querySelectorAll('.emphasis-badge').forEach(b=>{const i=Number(b.dataset.index);b.textContent=emphasisFor(phraseList[i],emphasisModes[i]||'auto',$('auto-emphasis').checked)?'強調対象':'';});$('emphasis-level-value').textContent=$('emphasis-level').value+' / 5';$('input-count').textContent=$('source').value.length.toLocaleString()+'文字';$('phrase-count').textContent=list.length+'件';$('preserve-value').textContent=$('preserve').value+'%';$('gap-value').textContent=$('gap').value+' px';$('variety-value').textContent=Number($('variety').value)<30?'控えめ':Number($('variety').value)<65?'ほどよく':'強め';}
function extractSource(){const mode=document.querySelector('[name=mode]:checked').value;phraseList=extract($('source').value,mode);emphasisModes=phraseList.map(()=>'auto');editPhrases();$('mode-help').textContent=mode==='quotes'?'「…」と『…』の中を抽出します。地の文や話者名は含めません。':mode==='paragraphs'?'空行で区切った段落をひとまとまりにし、段落内の改行を残します。':'空行を除いて、一行をひとつのことばとして使います。';status();schedule();}
function options(){const [width,height]=$('size').value.split(',').map(Number);return {width,height,seed,emphasis:phraseList.map((text,i)=>({text,mode:emphasisModes[i]||'auto'})).filter(p=>p.text.trim()).map(p=>emphasisFor(p.text,p.mode,$('auto-emphasis').checked)),emphasisLevel:Number($('emphasis-level').value),preserve:Number($('preserve').value)/100,variety:Number($('variety').value)/100,gap:Number($('gap').value),direction:$('direction').value,font:families[$('font').value],bold:$('bold').checked,mono,ink:$('ink').value,accent:$('accent').value,paper:$('paper').value};}
function resetPreview(){lastResult=null;const canvas=$('canvas');const [width,height]=$('size').value.split(',').map(Number);canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.fillStyle=$('paper').value;ctx.fillRect(0,0,width,height);canvas.setAttribute('aria-label','ことばが未入力のプレビュー');$('error').textContent='';$('small-warning').textContent='';$('result-info').textContent='ことばを入力すると、ここに画像が表示されます';$('download').disabled=true;}
function schedule(){revision++;clearTimeout(timer);if(!phrases().length){pending=false;resetPreview();return;}$('download').disabled=true;timer=setTimeout(()=>void draw(),240);}
async function draw(){if(!phrases().length){resetPreview();return null;}if(busy){pending=true;return null;}busy=true;const drawingRevision=revision;$('generate').disabled=true;$('shuffle').disabled=true;$('download').disabled=true;
 try{status();const list=phrases();validate(list);$('error').textContent='';await document.fonts.ready;await new Promise(r=>requestAnimationFrame(r));if(drawingRevision!==revision)return null;lastResult=render($('canvas'),list,options());$('canvas').setAttribute('aria-label',`${lastResult.count}件のことばを敷き詰めた画像：${list.slice(0,3).join('、')}`);$('result-info').textContent=`${lastResult.count}件（強調${lastResult.emphasized}件） · ${lastResult.width} × ${lastResult.height} px`;$('small-warning').textContent=lastResult.minFont<18?'小さな文字が含まれます。ことばを減らすと、読みやすくなります。':'';$('download').disabled=false;return lastResult;}
 catch(e){$('error').textContent=e.message;$('result-info').textContent='入力を確認してください · 前のプレビューを表示中';return null;}
 finally{busy=false;$('generate').disabled=false;$('shuffle').disabled=false;if(pending){pending=false;schedule();}}}
function notify(text){clearTimeout(toastTimer);$('toast').textContent=text;toastTimer=setTimeout(()=>$('toast').textContent='',3500);}
$('source').addEventListener('input',extractSource);document.querySelectorAll('[name=mode]').forEach(e=>e.addEventListener('change',extractSource));
for(const id of ['size','direction','font','ink','accent','paper','gap','variety','preserve','bold','auto-emphasis','emphasis-level'])$(id).addEventListener('input',()=>{status();schedule();});
$('mono').onclick=()=>{mono=!mono;$('mono').setAttribute('aria-pressed',String(mono));schedule();};
$('generate').onclick=()=>{clearTimeout(timer);void draw();};$('shuffle').onclick=()=>{seed=crypto.getRandomValues(new Uint32Array(1))[0];clearTimeout(timer);void draw();};
$('sample').onclick=()=>{if($('source').value&&$('source').value!==sample&&!confirm('入力中の文章をサンプルに置き換えますか？'))return;$('source').value=sample;document.querySelector('[name=mode][value=lines]').checked=true;extractSource();notify('サンプルのことばを表示しています');};
$('clear').onclick=()=>{if(($('source').value||phrases().length)&&!confirm('入力した文章と、使うことばをクリアしますか？'))return;$('source').value='';extractSource();$('source').focus();};
$('font-add').onclick=()=>$('font-file').click();$('font-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw new Error('フォントは20MBまでです。');$('font-status').textContent='読み込み中…';const name='MosaicCustom'+(++fontNumber);const face=new FontFace(name,await file.arrayBuffer());await face.load();document.fonts.add(face);families[name]=`"${name}",sans-serif`;const option=new Option(file.name.replace(/\.[^.]+$/,''),name);$('font').add(option);$('font').value=name;$('font-status').textContent='この画面を開いている間、有効';schedule();}catch(e){$('font-status').textContent='追加できませんでした';notify(e.message||'このフォントを読み込めません。');}finally{$('font-file').value='';}};
$('download').onclick=async()=>{if(busy||$('download').disabled)return;$('download').disabled=true;try{const blob=await new Promise(r=>$('canvas').toBlob(r,'image/png'));if(!blob)throw new Error('画像を作れませんでした。');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='lunaria-mosaic-'+new Date().toISOString().slice(0,10)+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);notify('PNGを書き出しました');}catch(e){notify(e.message);}finally{$('download').disabled=false;}};
$('source').value=sample;extractSource();
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'create_word_mosaic',title:'ことばのモザイクを作る',description:'文章から画像のプレビューを作り、画面の入力も更新します。既存入力を置き換えます。ファイルの保存は行いません。',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:100000},mode:{type:'string',enum:['lines','paragraphs','quotes']}},required:['text','mode'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(typeof input?.text!=='string'||input.text.length>100000||!['lines','paragraphs','quotes'].includes(input.mode))throw new Error('text と mode を確認してください。');if(busy)throw new Error('描画中です。少し待って再試行してください。');const list=extract(input.text,input.mode);validate(list);$('source').value=input.text;document.querySelector(`[name=mode][value=${input.mode}]`).checked=true;extractSource();clearTimeout(timer);const result=await draw();if(!result)throw new Error('描画できませんでした。');return result;}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
